// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_parmi_nous = "CgkIj8S51NQZEAIQCw"; // <GPGSID>
        public const string achievement_dernier_maitre_de_lair = "CgkIj8S51NQZEAIQBQ"; // <GPGSID>
        public const string achievement_architecte = "CgkIj8S51NQZEAIQBw"; // <GPGSID>
        public const string achievement_combattant_aguerri = "CgkIj8S51NQZEAIQCQ"; // <GPGSID>
        public const string achievement_apprentie = "CgkIj8S51NQZEAIQAg"; // <GPGSID>
        public const string achievement_roi_de_locan = "CgkIj8S51NQZEAIQBA"; // <GPGSID>
        public const string achievement_terraformeur = "CgkIj8S51NQZEAIQBg"; // <GPGSID>
        public const string achievement_survivant = "CgkIj8S51NQZEAIQAQ"; // <GPGSID>
        public const string achievement_dompteur_des_flammes = "CgkIj8S51NQZEAIQAw"; // <GPGSID>
        public const string achievement_alchimiste_confirm = "CgkIj8S51NQZEAIQCg"; // <GPGSID>
        public const string achievement_magistre = "CgkIj8S51NQZEAIQCA"; // <GPGSID>

}

